dump.keyCacheSize: 100 # Store keys of last 100 dumps 

fd.windowSize: 10 # Minutes back into the past that feeds should be dug on a normal run
fd.coldStartWindowSize: 640 # Minutes back into past that feeds should be dug on a cold start

clusterFormats.insertContent: TRUE # Should full content be inserted in the JSON of the Cluster?
